# Generated by Django 5.0.6 on 2024-06-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acitivityID', models.FloatField()),
                ('activityName', models.CharField(max_length=40)),
                ('startDate', models.DateTimeField()),
                ('sportType', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=250)),
                ('distance', models.FloatField()),
                ('movingTime', models.FloatField()),
                ('maxSpeed', models.FloatField()),
                ('averageSpeed', models.FloatField()),
            ],
        ),
    ]
