# Generated by Django 5.0.6 on 2024-06-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutlog',
            name='acitivityID',
        ),
        migrations.RemoveField(
            model_name='workoutlog',
            name='id',
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='activityID',
            field=models.UUIDField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
