# Generated by Django 5.0.6 on 2024-07-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_newworkout_lift1_alter_newworkout_lift1details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='averageSpeed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='maxSpeed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='movingTime',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
