# Generated by Django 5.0.6 on 2024-08-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_workoutlog_averagespeed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiftStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updateDate', models.DateTimeField(auto_now_add=True)),
                ('bench', models.FloatField()),
                ('press', models.FloatField()),
                ('squat', models.FloatField()),
                ('deadlift', models.FloatField()),
            ],
        ),
    ]
