# Generated by Django 5.0.6 on 2024-08-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_workoutlog_startdatemonth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='startDateMonth',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
