# Generated by Django 5.0.6 on 2024-08-29 14:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_workoutlog_startdatemonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='liftstats',
            name='updateDateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='liftstats',
            name='updateDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
