# Generated by Django 5.0.6 on 2025-03-14 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_liftstats_updatedatetime_alter_liftstats_updatedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newworkout',
            name='lift1',
        ),
        migrations.RemoveField(
            model_name='newworkout',
            name='lift1Details',
        ),
        migrations.RemoveField(
            model_name='newworkout',
            name='lift2',
        ),
        migrations.RemoveField(
            model_name='newworkout',
            name='lift2Details',
        ),
        migrations.RemoveField(
            model_name='newworkout',
            name='lift3',
        ),
        migrations.RemoveField(
            model_name='newworkout',
            name='lift3Details',
        ),
        migrations.RemoveField(
            model_name='newworkout',
            name='lift4',
        ),
        migrations.RemoveField(
            model_name='newworkout',
            name='lift4Details',
        ),
        migrations.RemoveField(
            model_name='newworkout',
            name='lift5',
        ),
        migrations.RemoveField(
            model_name='newworkout',
            name='lift5Details',
        ),
        migrations.RemoveField(
            model_name='newworkout',
            name='lift6',
        ),
        migrations.RemoveField(
            model_name='newworkout',
            name='lift6Details',
        ),
    ]
