# Generated by Django 5.0.6 on 2025-03-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_newworkout_lift1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newworkout',
            name='liftType',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
