# Generated by Django 5.0.6 on 2025-03-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_newworkout_lifttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='startDate',
            field=models.DateField(),
        ),
    ]
