# Generated by Django 5.0.6 on 2025-03-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_workoutlog_startdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='StravaAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestReceived', models.DateTimeField(auto_now_add=True)),
                ('userEmail', models.IntegerField()),
                ('accessToken', models.CharField(max_length=250)),
                ('refreshToken', models.CharField(max_length=250)),
                ('scopes', models.CharField(blank=True, max_length=250, null=True)),
                ('tokenExpiration', models.DateTimeField()),
            ],
        ),
    ]
