# Generated by Django 5.0.6 on 2025-03-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_stravaauth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stravaauth',
            name='scopes',
        ),
        migrations.AlterField(
            model_name='stravaauth',
            name='userEmail',
            field=models.CharField(max_length=250),
        ),
    ]
