# Generated by Django 5.0.6 on 2025-03-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_stravaauth_scopes_alter_stravaauth_useremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stravaauth',
            name='tokenExpiration',
            field=models.IntegerField(),
        ),
    ]
