
POST http://127.0.0.1:8000/api/login
Content-Type: application/json

{ "username": "test3", "password": "test3" }

###

POST http://127.0.0.1:8000/api/createUser
Content-Type: application/json

{ "username": "Test1dsa", "password": "pass1jhn", "email": "test14@test.com" }

###

GET http://127.0.0.1:8000/api/testToken
Content-Type: application/json
Authorization: token 0f2f21d1e833b542ef8ecff62977551ddaef5eb2

###

POST http://127.0.0.1:8000/api/liftingDashboard
Content-Type: application/json

{ "bench": 160, "press": 110, "squat": 230, "deadlift": 190 }

###

GET http://127.0.0.1:8000/api/liftingDashboard
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/runDashboard
Content-Type: application/json

###

POST http://127.0.0.1:8000/api/workoutLog
Content-Type: application/json

{ "activityId": 12154570513, "activityName": "Morning Run", "startDate": "2024-08-15T13:53:43Z", "sportType": "Run", "description": "Run", "distance": 6441.2, "movingTime": 2466, "averageSpeed": 2.612, "maxSpeed": 6.948 }

###

POST http://127.0.0.1:8000/api/stravaAuth
Content-Type: application/json

{"userEmail": "joshmcguinness23@gmail.com", "accessToken": "838109d281a5644c4837210a33b3c2f0e2732007", "refreshToken": "e4fa2d3452a1132b4e423bec89be0ef0f2efc0aa", "tokenExpiration": "1742322574"}

###

POST http://127.0.0.1:8000/api/register/
Content-Type: application/json

{"email": "joshmcguinness23@gmail.com", "username": "testJMCG77", "password1": "NopePassword", "password2": "NopePassword"}

###

POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{}

###

POST http://127.0.0.1:8000/api/logout/
Content-Type: application/json

{"Authorization: Token 9134580fae7da59ba01c9a0075f7e9b4e44afbc1"}